project:
  type: website
  output-dir: docs

website:
  title: "Miniproject miniwebsite"
  navbar:
    left:
      - href: index.qmd
        text: Project overview

      - href: data_documentation.qmd
        text: Data documentation

      - href: analysis.qmd
        text: Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

